---
title: "About Industry Studies"
---

### History
In 1990, the Alfred P. Sloan Foundation began a program of sponsoring academic research on industries through research centers at major universities. Each of the earliest Sloan Industry Centers specialized in the analysis of a particular industry. Eventually, the Sloan program grew to include twenty-six centers spanning a broad set of traditional and emerging industries, and research interests also expanded to include cross-industry analysis.

As program activities developed, the list of scholars engaged in related research expanded well beyond the industry centers to include over 1200 Sloan Industry Studies Affiliates. Encouraged by this growth and the very positive response of participants to annual industry studies conferences, the Industry Studies Association was established by Industry Studies Affiliates in order to promote the kind of scholarship that had become emblematic of the Sloan program.

The Industry Studies Association was incorporated in October 2007, became tax exempt in September 2008 as a 501 (c) (3) organization, and began accepting general membership in April 2009.

### What is Industry Studies?
Scholars who pursue industry studies come from a wide variety of disciplines such as management, economics, engineering, industrial and labor relations, operations research, law, economic geography, and public policy. While this list is by no means comprehensive, it does suggest the very broad range of disciplines that find value in collaborating around industry studies research.

Industry studies scholars may focus their attention on particular industries or occupations, or conduct cross-industry analysis. Across research interests and disciplines, industry studies scholars make the kind of personal investment of time that is necessary to learn about the market and firm institutions in the industry or industries they study. This kind of engagement, which includes close interaction with industry practitioners and often includes direct observation at the plant, firm, or establishment level, allows industry studies scholars to pursue academic research from a broad and deep basis of understanding about the subject of their analysis.
