---
title: "Mission and Vision Statement"
---

### Mission
The Industry Studies Association (ISA) is dedicated to advancing industry studies research, a field characterized by its examination of the context of a specific industry or a phenomenon affecting multiple industries. Such research often spans multiple disciplinary perspectives, offering insights that can support evidence-based policymaking and managerial decision-making.

The ISA aims to elevate the profile of industry studies research and its positive impact on realized public policy and industry outcomes. We accomplish this by identifying, connecting, and recognizing scholars undertaking industry studies research, facilitating interdisciplinary dialogue and exchanges rich in industry context, and fostering direct interactions between academia, industry, and policymakers.

### Vision
We aspire to a future where:

- Industry studies research is regularly published in top academic journals;
- The ISA’s conferences are *the leading* venue where top academic researchers, key policymakers, business media, and other key thought leaders exchange ideas and insights;
- The ISA engages a global audience, with periodic events outside of the United States;
- ISA members regularly are called upon by the media and others to provide insight to phenomena in their industry;
- Public policymakers, managers, and thought leaders around the globe actively seek out industry studies scholars to help improve public policy;
- Industry studies activities, such as commenting on proposed public policies in a researcher’s domain, are rewarded.
